version: "3.9" # ou 3.10, dependendo da vers√£o mais recente que seu docker-compose suporta
services:
  mf_videos:
    build: ./micro-frontend/mf_videos
    ports:
      - "8081:8081"

  # mf_drawer:
  #   build: ./micro-frontend/mf_drawer
  #   ports:
  #     - "8080:8080"
